black:      $000000
gray:       $808080
silver:     $c0c0c0
white:      $ffffff

red:        $ff0000
green:      $00ff00
blue:       $0000ff
magenta:    $ff00ff
yellow:     $ffff00
cyan:       $00ffff

orange:     $ff7f00
violet:     $7f00ff
purple:     $ff007f

# specials
bg1:        $050505
bg2:        $202020
